language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn run build
  - yarn test --coverage
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
